apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: node
  janus-idp.io/tekton: node
  backstage.io/kubernetes-id: node
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: node
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
